org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

minecraft_version=26.2
loader_version=0.19.5
loom_version=1.18-SNAPSHOT

mod_version=1.14.2
maven_group=com.gafipro
archives_base_name=what-is-he-doing

fabric_api_version=0.161.0+26.2
gson_version=2.13.2
webrtc_java_version=0.14.0
signaling_url=ws://127.0.0.1:8787

# CI validation marker
